import logoCardbot from "@/ui/images/logo_cardbot.png";
import currencyLogo from "@/ui/icons/currency_logo.svg";
import exchangeLogo from "@/ui/icons/exchange_logo.svg";
import trading from "@/ui/icons/trading.svg";
import copy_trading from "@/ui/icons/copy_trading.svg";
import cross_chain from "@/ui/icons/cross_chain.svg";

export const productsType = [
	{name: 'Automatic Trading', link: '/automatictrading', icon: trading.src, description: 'Automated trading system'},
	{name: 'Copy Trading', link: '/copytrading', icon: copy_trading.src, description: 'Long-term strategies from Company'},
	{name: 'Cross-chain DEX Trading', link: '/crosschain-dex', icon: cross_chain.src, description: 'Coming soon'},
]


export interface goodsType {
	logo: string,
	name: string,
	descripption: string,
	profit: number,
	maxDrawdown: number,
	currencyLogo: string,
	currencyName: string,
	exchangeLogo: string,
	exchangeName: string,
	winningTrades: number, 
	losingTrades: number,
	wlRatio: string,
}

export const goods = [
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
	{
		logo: logoCardbot.src,
		name: 'OKX Low-Risk Index Copy Bot',
		descripption: 'The bot analyzes the market for cryptocurrencies that offer the lowest risks and medium good profits.',
		profit: 242.24,
		maxDrawdown: 7.21,
		currencyLogo: currencyLogo.src,
		currencyName: 'BNB',
		exchangeLogo: exchangeLogo.src,
		exchangeName: 'OKX',
		winningTrades: 92, 
		losingTrades: 8,
		wlRatio: '721/23',
	},
] as goodsType[]